import { client } from "../app"
import * as esijs from "esijs"
import * as discord from "discord.js"
import * as pathfinder from "../pathfinderParse/pathfinderParse"
import { getAllianceName, getCharacterName, getCorporationName } from "../utils/utils"

function isFriendlyKill(killData): boolean {
    // A friendly kill is one where either the defender or any of the attackers are friendly

    // First, we loop through all the attackers and check whether any of them are friendly to 
    // generate a boolean representing if the any of the attackers are friendly 
    let containsFriendlyAttacker = false;
    (killData.attackers).forEach(attacker => {
        if (attacker.alliance_id === Number(process.env.FRIENDLY_ALLIANCE)) {
            containsFriendlyAttacker = true;
        }
    });

    // This could be rewritten without the if statements, but in the interest of readability 
    // it is kept in this form
    if (killData.victim.alliance_id === Number(process.env.FRIENDLY_ALLIANCE) || containsFriendlyAttacker) {
        return true;
    }
    else {
        return false;
    }
}

function isKillInChain(killData): boolean {
    // Simple function that checks whether a given killData took place within the chain
    if (pathfinder.getConnectedSystems().includes(killData.solar_system_id)) {
        return true;
    }
    return false;
}

export async function parseKill(event: { data: any; type: string; }) {
    // Takes the data returned by the WebSocket, parses the JSON and then generates 
    // an alert if the kill both was not generated by Exit, and occurred in the chain

    let killData = JSON.parse(event.data);

    if (!isFriendlyKill(killData) && isKillInChain(killData)) {
        generateAlert(killData)
    }
}

async function generateAlert(killData: any) {
    // Generates and sends an alert based on the killData provided
    const alertEmbed = {
        title: (await esijs.universe.types.typeInfo(killData.victim.ship_type_id)).name
            + " killed in "
            + (await esijs.universe.systems.systemInfo(killData.solar_system_id)).name
            + " - "
            + pathfinder.getJumpsFromHome(killData.solar_system_id)
            + " Jumps from Deep",
        color: 0xff0000,
        url: killData.zkb.url,
        thumbnail: {
            url: 'https://images.evetech.net/types/'
                + killData.victim.ship_type_id
                + '/render?size=128',
        },
        "fields": [
            {
                name: 'Attacker (final blow)',
                value: await getCharacterName(killData.attackers[0].character_id),
                inline: true
            },
            {
                name: 'Corporation',
                value: await getCorporationName(killData.attackers[0].corporation_id),
                inline: true
            },
            {
                name: 'Alliance',
                value: await getAllianceName(killData.attackers[0].alliance_id),
                inline: true
            },
            {
                name: '\u200b',
                value: '\u200b',
                inline: false
            },
            {
                name: 'Victim',
                value: await getCharacterName(killData.victim.character_id),
                inline: true
            },
            {
                name: 'Corporation',
                value: await getCorporationName(killData.victim.corporation_id),
                inline: true
            },
            {
                name: 'Alliance',
                value: await getAllianceName(killData.victim.alliance_id),
                inline: true
            },
        ],
    };
    let channel = <discord.TextChannel>client.channels.cache.get(process.env.BOT_CHANNEL);
    channel.send({ embed: alertEmbed });
}